# Generated by Django 5.0 on 2024-01-18 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_address_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_charge',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
