# Generated by Django 5.0 on 2024-01-18 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_order_session_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='session_id',
        ),
    ]
