# Generated by Django 5.0 on 2024-01-05 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='imgg',
            field=models.FileField(upload_to='blog'),
        ),
    ]
