# Generated by Django 5.0 on 2024-01-05 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_tag_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='detail',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
