# Generated by Django 5.0 on 2023-12-29 06:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='imgg',
            field=models.FileField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
