# Generated by Django 5.0 on 2023-12-29 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_banner_imgg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='imgg',
            field=models.FileField(blank=True, null=True, upload_to='banner_image'),
        ),
    ]
