# Generated by Django 5.0 on 2023-12-29 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_banner_imgg'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='imgg',
            field=models.FileField(blank=True, null=True, upload_to='product'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='imgg',
            field=models.FileField(blank=True, null=True, upload_to='banner'),
        ),
    ]
