# Generated by Django 5.0 on 2024-01-02 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_rating_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_category',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
