# Generated by Django 5.0 on 2024-01-04 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_p_images_remove_product_imgg_product_product_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='imgg',
            field=models.FileField(blank=True, null=True, upload_to='brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_images',
            field=models.ManyToManyField(to='products.p_images'),
        ),
    ]
