# Generated by Django 5.0 on 2024-01-05 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_brand_imgg_alter_product_product_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='imgg',
            field=models.FileField(blank=True, null=True, upload_to='category'),
        ),
    ]
